---
title: "Exploratory Analysis"
output: html_document
---

## Climate Change Effects

Give your project a concise, interesting title that summarizes the entirety of your project

### Ryan Kang (kangryan@uw.edu), Annabelle Fallstrom(afalls@uw.edu), Tyler Nguyen (tyjn@uw.edu), Don Vo (donvo@uw.edu)

Names of your team members

### 5/17/2024

Spring 2024

### Abstract

The primary objective is to rigorously analyze the effects of climate change across diverse facets and observe its impact on our planet’s various environmental domains–ecological, hydrological, oceanic, glaciological, and atmospheric systems. Through systematic data collection, we seek to highlight the specific impacts of climate change on the various environmental factors and explore their interrelations. Ultimately, the insights from our research are intended to inform and refine strategies for mitigation, adaptation, and response to the emergent challenges posed by our Earth’s devastating direction of climate change.

### Climate Change, Global Warming, Carbon Footprint


3-5 keywords that summarize your project.
(e.g., "Keywords: human physiology; bicycle exercise; Gen Z; times-series data")

### Introduction  

Briefly introduce your project.  Include 3-5 research questions. What motivates the questions? Why are they important? (at least 200 words)

### Related Work  

Describe your topic and related work in this space. You must include 3 citations to related work (URLs to similar work, high quality articles from the popular press, research papers, etc. ) Please use a standard citation style of your choice. (at least 200 words)

### The Dataset

Where did you find the data? Please include a link to the data source  
Who collected the data?  
How was the data collected or generated?  
Why was the data collected?  
How many observations (rows) are in your data?  
How many features (columns) are in the data?  
What, if any, ethical questions or questions of power do you need to consider when working with this data?  
What are possible limitations or problems with this data?   (at least 200 words)

### Implications

Assuming you answer your research questions, briefly describe the expected or possible implications for technologists, designers, and policymakers. (at least 150 words)

### Limitations & Challenges
What challenges or limitations might you need to address with your project idea more broadly? Briefly discuss. (at least 150 words)

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1

Include a chart

Describe why you chose this chart and what information it reveals

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Chart 2

Include a chart

Describe why you chose this chart and what information it reveals

### Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
